# Generated by Django 6.0.6 on 2026-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalisisInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_terreno_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_construccion_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_total_estimado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gastos_notariales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "comisiones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reparaciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "otros_gastos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "inversion_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "utilidad_potencial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento_mercado",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="%", max_digits=7
                    ),
                ),
                (
                    "roi",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="%", max_digits=7
                    ),
                ),
                (
                    "roi_anualizado",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="%", max_digits=7
                    ),
                ),
                (
                    "anos_recuperacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tasa_bancaria_referencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "semaforo",
                    models.CharField(
                        choices=[
                            ("verde", "Verde — Alta oportunidad"),
                            ("amarillo", "Amarillo — Requiere análisis"),
                            ("rojo", "Rojo — No recomendable"),
                            ("gris", "Gris — Datos insuficientes"),
                        ],
                        default="gris",
                        max_length=10,
                    ),
                ),
                ("es_oportunidad", models.BooleanField(default=False)),
                ("es_prioritaria", models.BooleanField(default=False)),
                ("datos_completos", models.BooleanField(default=False)),
                (
                    "factor_estado_fisico",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "factor_antiguedad",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "factor_ubicacion",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "factor_riesgo",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                ("riesgos", models.TextField(blank=True)),
                ("recomendacion", models.TextField(blank=True)),
                ("comentarios_analista", models.TextField(blank=True)),
                ("calculado_en", models.DateTimeField(auto_now=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Análisis de inversión",
                "verbose_name_plural": "Análisis de inversión",
                "ordering": ["-es_prioritaria", "-descuento_mercado"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionBusqueda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_inmueble",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("terreno", "Terreno"),
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("local", "Local comercial"),
                            ("nave", "Nave industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("radio_metros", models.PositiveIntegerField(default=2000)),
                (
                    "descuento_minimo",
                    models.DecimalField(decimal_places=2, default=15, max_digits=5),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("quincenal", "Quincenal"),
                            ("mensual", "Mensual"),
                        ],
                        default="semanal",
                        max_length=20,
                    ),
                ),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Configuración de búsqueda",
                "verbose_name_plural": "Configuraciones de búsqueda",
                "ordering": ["-activa", "-creada_en"],
            },
        ),
    ]
