# Generated by Django 6.0.6 on 2026-06-09 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analisis", "0001_initial"),
        ("geografia", "0001_initial"),
        ("propiedades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analisisinversion",
            name="analista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analisis_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analisisinversion",
            name="propiedad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analisis",
                to="propiedades.propiedad",
            ),
        ),
        migrations.AddField(
            model_name="configuracionbusqueda",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busquedas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="configuracionbusqueda",
            name="zona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busquedas",
                to="geografia.zonamercado",
            ),
        ),
        migrations.AddIndex(
            model_name="analisisinversion",
            index=models.Index(
                fields=["es_oportunidad", "es_prioritaria", "semaforo"],
                name="analisis_an_es_opor_f3a038_idx",
            ),
        ),
    ]
