# Generated by Django 5.1.15 on 2026-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisinversion',
            name='costo_remodelacion_m2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo por m² aplicado (MXN)', max_digits=12),
        ),
        migrations.AddField(
            model_name='analisisinversion',
            name='nivel_remodelacion_aplicado',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna — lista para habitar'), ('ligera', 'Ligera — cosmética (pintura, detalles)'), ('media', 'Media — baños, cocina, pisos, instalaciones parciales'), ('completa', 'Completa — remodelación integral / estructural')], help_text='Nivel de obra usado para estimar el presupuesto', max_length=20),
        ),
        migrations.AddField(
            model_name='analisisinversion',
            name='presupuesto_remodelacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto total de remodelación estimado (MXN)', max_digits=14),
        ),
        migrations.AddField(
            model_name='analisisinversion',
            name='remodelacion_estimada',
            field=models.BooleanField(default=False, help_text='True si se usó el costo fallback global (la zona no tiene costo capturado)'),
        ),
        migrations.AlterField(
            model_name='analisisinversion',
            name='reparaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto de remodelación (ver desglose abajo)', max_digits=12),
        ),
    ]
