# Generated by Django 6.0.6 on 2026-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nueva_oportunidad", "Nueva oportunidad"),
                            ("descuento_relevante", "Descuento relevante"),
                            ("roi_atractivo", "ROI atractivo"),
                            ("baja_precio", "Baja de precio"),
                            ("nueva_zona", "Nueva propiedad en zona"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("email", "Correo electrónico"),
                            ("whatsapp", "WhatsApp"),
                            ("interna", "Notificación interna"),
                        ],
                        default="interna",
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("enviada", models.BooleanField(default=False)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-creada_en"],
            },
        ),
    ]
