# Generated by Django 6.0.6 on 2026-06-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alertas", "0001_initial"),
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="propiedad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertas",
                to="propiedades.propiedad",
            ),
        ),
    ]
