# Generated by Django 5.0.7 on 2026-06-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="canal",
            field=models.CharField(
                choices=[
                    ("interna", "Notificación interna"),
                    ("email", "Correo electrónico"),
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="interna",
                max_length=20,
            ),
        ),
    ]
