# Generated by Django 4.2.30 on 2026-08-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alter_alerta_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('nueva_oportunidad', 'Nueva oportunidad'), ('descuento_relevante', 'Descuento relevante'), ('roi_atractivo', 'ROI atractivo'), ('baja_precio', 'Baja de precio'), ('nueva_zona', 'Nueva propiedad en zona'), ('presupuesto_contingencia', 'Presupuesto consumiendo contingencia'), ('presupuesto_rebasado', 'Presupuesto rebasado'), ('partida_desviada', 'Partida con desviación relevante')], max_length=30),
        ),
    ]
