# Generated by Django 4.2.30 on 2026-08-03 05:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0003_propiedad_nivel_remodelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('demolicion', 'Demolición y retiro de escombro'), ('reparaciones', 'Reparaciones estructurales / humedades'), ('cocina', 'Cocina'), ('banos', 'Baños'), ('pisos', 'Pisos y recubrimientos'), ('electrica_act', 'Instalación eléctrica (actualización)'), ('hidro_act', 'Instalación hidrosanitaria (actualización)'), ('pintura', 'Pintura y acabados'), ('preliminares', 'Preliminares'), ('cimentacion', 'Cimentación'), ('estructura', 'Estructura'), ('albanileria', 'Albañilería'), ('hidrosanitaria', 'Instalación hidrosanitaria'), ('electrica', 'Instalación eléctrica'), ('acabados', 'Acabados'), ('carpinteria', 'Carpintería y cancelería'), ('exteriores', 'Exteriores'), ('limpieza', 'Limpieza final y entrega')], max_length=30)),
                ('unidad', models.CharField(choices=[('m2', 'm²'), ('m3', 'm³'), ('ml', 'Metro lineal'), ('pza', 'Pieza'), ('lote', 'Lote'), ('jgo', 'Juego'), ('salida', 'Salida'), ('serv', 'Servicio')], max_length=10)),
                ('pu_material', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='MXN por unidad', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pu_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='MXN por unidad', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pu_equipo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Herramienta y equipo, MXN por unidad', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vigencia', models.DateField(help_text='Fecha a la que corresponde el precio; sirve para saber si ya envejeció')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto del catálogo',
                'verbose_name_plural': 'Catálogo de conceptos',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('demolicion', 'Demolición y retiro de escombro'), ('reparaciones', 'Reparaciones estructurales / humedades'), ('cocina', 'Cocina'), ('banos', 'Baños'), ('pisos', 'Pisos y recubrimientos'), ('electrica_act', 'Instalación eléctrica (actualización)'), ('hidro_act', 'Instalación hidrosanitaria (actualización)'), ('pintura', 'Pintura y acabados'), ('preliminares', 'Preliminares'), ('cimentacion', 'Cimentación'), ('estructura', 'Estructura'), ('albanileria', 'Albañilería'), ('hidrosanitaria', 'Instalación hidrosanitaria'), ('electrica', 'Instalación eléctrica'), ('acabados', 'Acabados'), ('carpinteria', 'Carpintería y cancelería'), ('exteriores', 'Exteriores'), ('limpieza', 'Limpieza final y entrega')], max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('unidad', models.CharField(choices=[('m2', 'm²'), ('m3', 'm³'), ('ml', 'Metro lineal'), ('pza', 'Pieza'), ('lote', 'Lote'), ('jgo', 'Juego'), ('salida', 'Salida'), ('serv', 'Servicio')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio unitario congelado al momento de armar el presupuesto', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('concepto', models.ForeignKey(blank=True, help_text='Origen en el catálogo; vacío si es manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='presupuestos.catalogoconcepto')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['presupuesto', 'categoria', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_obra', models.CharField(choices=[('remodelacion', 'Remodelación'), ('obra_nueva', 'Obra nueva')], default='remodelacion', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Área de intervención; permite comparar el costo real por m² (§4.6)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pct_indirectos', models.DecimalField(decimal_places=2, default=Decimal('12'), help_text='Supervisión, traslados, permisos, herramienta (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pct_contingencia', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Reserva para imprevistos REALES, no para mejoras (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pct_utilidad', models.DecimalField(decimal_places=2, default=Decimal('12'), help_text='Margen del inversionista (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('aplica_iva', models.BooleanField(default=False, help_text='Solo si se factura o se compra con factura')),
                ('pct_iva', models.DecimalField(decimal_places=2, default=Decimal('16'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('es_activo', models.BooleanField(default=False, help_text='El que alimenta el ROI de la propiedad (Fase 3)')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(blank=True, help_text='Opcional: un presupuesto puede existir sin propiedad ligada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('importe_real', models.DecimalField(decimal_places=2, help_text='MXN efectivamente pagados', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('factura', models.CharField(blank=True, help_text='Folio o UUID de la factura, si la hay', max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(blank=True, help_text='Opcional: a qué renglón se imputa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='presupuestos.partidapresupuesto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='presupuestos.presupuesto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de gasto',
                'verbose_name_plural': 'Registros de gasto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='partidapresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='presupuestos.presupuesto'),
        ),
        migrations.CreateModel(
            name='OrdenCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('motivo', models.TextField(help_text='Por qué se requiere; distingue imprevisto de mejora')),
                ('importe', models.DecimalField(decimal_places=2, help_text='MXN. Negativo si el cambio REDUCE el alcance', max_digits=14)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20)),
                ('fecha', models.DateField()),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_cambio_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_cambio', to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name': 'Orden de cambio',
                'verbose_name_plural': 'Órdenes de cambio',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogoconcepto',
            index=models.Index(fields=['categoria', 'activo'], name='presupuesto_categor_7bf29f_idx'),
        ),
        migrations.AddIndex(
            model_name='registrogasto',
            index=models.Index(fields=['presupuesto', '-fecha'], name='presupuesto_presupu_f3a4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['propiedad', 'es_activo'], name='presupuesto_propied_3dfb52_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['estado', '-creado_en'], name='presupuesto_estado_0f3ba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='presupuesto',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activo', True), ('propiedad__isnull', False)), fields=('propiedad',), name='unico_presupuesto_activo_por_propiedad'),
        ),
        migrations.AddIndex(
            model_name='partidapresupuesto',
            index=models.Index(fields=['presupuesto', 'categoria'], name='presupuesto_presupu_45266d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencambio',
            index=models.Index(fields=['presupuesto', 'estado'], name='presupuesto_presupu_c99051_idx'),
        ),
    ]
