# Generated by Django 4.2.30 on 2026-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencambio',
            name='fuente',
            field=models.CharField(choices=[('contingencia', 'Con cargo a la contingencia (imprevisto)'), ('capital_adicional', 'Capital adicional (amplía el presupuesto aprobado)')], default='contingencia', help_text='De dónde sale el dinero (§4.2). Solo "adicional" amplía el presupuesto aprobado; con cargo a contingencia consume la reserva.', max_length=20),
        ),
    ]
