# Generated by Django 6.0.6 on 2026-06-09 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geografia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuenteDatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("portal", "Portal inmobiliario"),
                            ("red_social", "Red social"),
                            ("agencia", "Agencia inmobiliaria"),
                            ("avaluo", "Fuente de avalúo"),
                            ("manual", "Captura manual"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url_base", models.URLField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("requiere_api", models.BooleanField(default=False)),
                (
                    "terminos_uso",
                    models.TextField(
                        blank=True, help_text="Notas sobre restricciones legales"
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fuente de datos",
                "verbose_name_plural": "Fuentes de datos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TasaReferenciaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institucion",
                    models.CharField(default="Promedio bancario", max_length=150),
                ),
                (
                    "tasa_anual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tasa de ahorro anual en %",
                        max_digits=5,
                    ),
                ),
                ("fecha_vigencia", models.DateField()),
                ("fuente", models.CharField(blank=True, max_length=200)),
                ("es_default", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tasa de referencia bancaria",
                "verbose_name_plural": "Tasas de referencia bancaria",
                "ordering": ["-fecha_vigencia"],
            },
        ),
        migrations.CreateModel(
            name="ComparativoMercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("terreno", "Terreno"),
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("local", "Local comercial"),
                            ("nave", "Nave industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "precio_promedio_m2",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_propiedades", models.PositiveIntegerField(default=0)),
                ("periodo", models.DateField(help_text="Inicio del periodo analizado")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparativos",
                        to="geografia.zonamercado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparativo de mercado",
                "verbose_name_plural": "Comparativos de mercado",
                "ordering": ["-periodo"],
            },
        ),
        migrations.CreateModel(
            name="ValorMetroCuadrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("terreno", "Terreno"),
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("local", "Local comercial"),
                            ("nave", "Nave industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_terreno_m2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor promedio por m² de terreno (MXN)",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_construccion_m2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor promedio por m² construido (MXN)",
                        max_digits=12,
                    ),
                ),
                (
                    "valor_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "valor_promedio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "valor_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "antiguedad_anos",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estado_fisico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excelente", "Excelente"),
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("malo", "Malo"),
                            ("demoler", "Requiere demolición parcial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "servicios",
                    models.TextField(
                        blank=True, help_text="Agua, luz, drenaje, gas, etc."
                    ),
                ),
                ("uso_suelo", models.CharField(blank=True, max_length=100)),
                ("fecha_actualizacion", models.DateField()),
                (
                    "confiabilidad",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1=baja, 5=alta confiabilidad",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valores_referencia",
                        to="mercado.fuentedatos",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores_m2",
                        to="geografia.zonamercado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor por metro cuadrado",
                "verbose_name_plural": "Valores por metro cuadrado",
                "ordering": ["-fecha_actualizacion"],
                "indexes": [
                    models.Index(
                        fields=["zona", "tipo_inmueble", "-fecha_actualizacion"],
                        name="mercado_val_zona_id_5e8302_idx",
                    )
                ],
            },
        ),
    ]
