# Generated by Django 6.0.6 on 2026-06-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0002_initial"),
        ("geografia", "0001_initial"),
        ("mercado", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeEjecucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_proceso", "En proceso"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                            ("omitido", "Omitido"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
                ("encontrados", models.PositiveIntegerField(default=0)),
                ("nuevos", models.PositiveIntegerField(default=0)),
                ("actualizados", models.PositiveIntegerField(default=0)),
                ("errores", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True)),
                ("iniciado_en", models.DateTimeField(auto_now_add=True)),
                ("finalizado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "configuracion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrapes",
                        to="analisis.configuracionbusqueda",
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejecuciones",
                        to="mercado.fuentedatos",
                    ),
                ),
                (
                    "zona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrapes",
                        to="geografia.zonamercado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de scraping",
                "verbose_name_plural": "Ejecuciones de scraping",
                "ordering": ["-iniciado_en"],
            },
        ),
    ]
