# Generated by Django 5.1.15 on 2026-07-10 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
        ('mercado', '0002_scrapeejecucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoRemodelacionM2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_obra', models.CharField(choices=[('ninguna', 'Ninguna — lista para habitar'), ('ligera', 'Ligera — cosmética (pintura, detalles)'), ('media', 'Media — baños, cocina, pisos, instalaciones parciales'), ('completa', 'Completa — remodelación integral / estructural')], max_length=20)),
                ('costo_m2', models.DecimalField(decimal_places=2, default=0, help_text='Costo de remodelación por m² de construcción (MXN)', max_digits=12)),
                ('fecha_actualizacion', models.DateField()),
                ('confiabilidad', models.PositiveSmallIntegerField(default=3, help_text='1=baja, 5=alta confiabilidad', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_remodelacion', to='mercado.fuentedatos')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_remodelacion', to='geografia.zonamercado')),
            ],
            options={
                'verbose_name': 'Costo de remodelación por m²',
                'verbose_name_plural': 'Costos de remodelación por m²',
                'ordering': ['zona', 'nivel_obra', '-fecha_actualizacion'],
                'indexes': [models.Index(fields=['zona', 'nivel_obra', '-fecha_actualizacion'], name='mercado_cos_zona_id_de0dbc_idx')],
            },
        ),
    ]
