# Generated by Django 5.0.7 on 2026-06-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="alertas_solo_prioritarias",
            field=models.BooleanField(
                default=False,
                help_text="Solo alertar oportunidades verdes/prioritarias",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="canal_alerta_preferido",
            field=models.CharField(
                choices=[
                    ("interna", "Solo en la app (gratis)"),
                    ("email", "Correo electrónico (gratis)"),
                    ("telegram", "Telegram (gratis)"),
                    ("email_telegram", "Email + Telegram"),
                ],
                default="email",
                help_text="Canal principal de alertas",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="notificaciones_telegram",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID de chat de Telegram (obtener con @userinfobot)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="notificaciones_whatsapp",
            field=models.BooleanField(
                default=False, help_text="WhatsApp vía Twilio — tiene costo por mensaje"
            ),
        ),
    ]
