# Generated by Django 6.0.6 on 2026-06-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_anterior",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("precio_nuevo", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Historial de precio",
                "verbose_name_plural": "Historial de precios",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_publicado",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio en MXN", max_digits=14
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=400)),
                (
                    "m2_terreno",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "m2_construccion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "habitaciones",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("banos", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("niveles", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "estacionamientos",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "antiguedad_anos",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estado_fisico",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente"),
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("malo", "Malo"),
                            ("demoler", "Requiere demolición parcial"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("terreno", "Terreno"),
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("local", "Local comercial"),
                            ("nave", "Nave industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url_anuncio", models.URLField(blank=True)),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True, help_text="Enlace público a fotografía"
                    ),
                ),
                (
                    "contacto_publico",
                    models.CharField(
                        blank=True,
                        help_text="Solo si es público y permitido",
                        max_length=200,
                    ),
                ),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_deteccion", models.DateTimeField(auto_now_add=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("nueva", "Nueva"),
                            ("en_analisis", "En análisis"),
                            ("descartada", "Descartada"),
                            ("oportunidad", "Oportunidad"),
                            ("comprada", "Comprada"),
                            ("vendida", "Vendida"),
                            ("archivada", "Archivada"),
                        ],
                        default="nueva",
                        max_length=20,
                    ),
                ),
                (
                    "semaforo",
                    models.CharField(
                        choices=[
                            ("verde", "Verde — Alta oportunidad"),
                            ("amarillo", "Amarillo — Requiere análisis"),
                            ("rojo", "Rojo — No recomendable"),
                            ("gris", "Gris — Datos insuficientes"),
                        ],
                        default="gris",
                        max_length=10,
                    ),
                ),
                (
                    "riesgo_documental",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="1=muy bajo, 5=muy alto"
                    ),
                ),
                ("riesgo_legal", models.PositiveSmallIntegerField(default=2)),
                ("riesgo_fisico", models.PositiveSmallIntegerField(default=2)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Propiedad",
                "verbose_name_plural": "Propiedades",
                "ordering": ["-fecha_deteccion"],
            },
        ),
    ]
