# Generated by Django 6.0.6 on 2026-06-09 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geografia", "0001_initial"),
        ("mercado", "0001_initial"),
        ("propiedades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="capturado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propiedades_capturadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="fuente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propiedades",
                to="mercado.fuentedatos",
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="zona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="propiedades",
                to="geografia.zonamercado",
            ),
        ),
        migrations.AddField(
            model_name="historialprecio",
            name="propiedad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_precios",
                to="propiedades.propiedad",
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["zona", "estatus", "semaforo"],
                name="propiedades_zona_id_938696_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["precio_publicado", "-fecha_deteccion"],
                name="propiedades_precio__25fff9_idx",
            ),
        ),
    ]
