# Generated by Django 5.1.15 on 2026-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='nivel_remodelacion',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna — lista para habitar'), ('ligera', 'Ligera — cosmética (pintura, detalles)'), ('media', 'Media — baños, cocina, pisos, instalaciones parciales'), ('completa', 'Completa — remodelación integral / estructural')], help_text='Nivel de obra requerido. Si se deja vacío, se deriva del estado físico.', max_length=20),
        ),
    ]
